# Data Cleaning

In [1]:
import pandas as pd
import re

In [59]:
df = pd.read_csv("EV Database2.csv")

In [61]:
df.head()

,name,efficiency,real_range,weight,acceleration,one_stop_range,fast_charge,tow_weight,cargo_volume,price_per_range,germany_price_euros,netherlands_price_euros,uk_gbp,availability,drive,market_segment,seats,heat_pump,towbar,safety_rating
0,Tesla Model 3 RWD,218 Wh/mi,275 mi,"1,847 kg",6.2 sec,331 mi,60.0 kWh,"1,000 kg",682 L,£125 /mi,"€37,970","€36,990","£37,990",Available to order since December 2025,Rear Wheel Drive,D,5,Heat pump available,Towbar possible,-1
1,BMW iX3 50 xDrive,279 Wh/mi,390 mi,"2,360 kg",4.9 sec,478 mi,108.7 kWh,"2,000 kg",578 L,£155 /mi,"€70,900","€70,501","£58,755",Available to order since September 2025,All Wheel Drive,D,5,Heat pump available,Towbar possible,-1
2,MG MG4 Electric 64 kWh,280 Wh/mi,220 mi,"1,726 kg",7.9 sec,249 mi,61.7 kWh,500 kg,363 L,£147 /mi,"€39,990","€37,570","£29,745",Discontinued (October 2022 - February 2026),Rear Wheel Drive,C,5,Heat pump available,Towbar possible,5
3,BMW iX xDrive40,323 Wh/mi,220 mi,"2,440 kg",6.1 sec,237 mi,71.0 kWh,"2,500 kg",500 L,£320 /mi,"€77,300","€84,998","£69,905",Discontinued (October 2021 - January 2025),All Wheel Drive,E,5,Heat pump available,Towbar possible,5
4,Fiat 500e Hatchback 42 kWh,257 Wh/mi,145 mi,"1,365 kg",9.0 sec,162 mi,37.3 kWh,0 kg,185 L,£181 /mi,"€34,990","€27,999","£23,995",Available to order since November 2020,Front Wheel Drive,B,4,Heat pump not available,Towbar not possible,4

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 182250 entries, 0 to 182249
Data columns (total 20 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   name                     182250 non-null  object
 1   efficiency               182250 non-null  object
 2   real_range               182250 non-null  object
 3   weight                   182250 non-null  object
 4   acceleration             182250 non-null  object
 5   one_stop_range           182250 non-null  object
 6   fast_charge              182250 non-null  object
 7   tow_weight               182250 non-null  object
 8   cargo_volume             182250 non-null  object
 9   price_per_range          182250 non-null  object
 10  germany_price_euros      171855 non-null  object
 11  netherlands_price_euros  163890 non-null  object
 12  uk_gbp                   132570 non-null  object
 13  availability             182250 non-null  object
 14  drive                    182250 non-null  object
 15  market_segment           182250 non-null  object
 16  seats                    182250 non-null  int64
 17  heat_pump                182250 non-null  object
 18  towbar                   182250 non-null  object
 19  safety_rating            182250 non-null  int64
dtypes: int64(2), object(18)
memory usage: 27.8+ MB

In [63]:
round((df.isnull().sum()/len(df))*100,2)

name                        0.00
efficiency                  0.00
real_range                  0.00
weight                      0.00
acceleration                0.00
one_stop_range              0.00
fast_charge                 0.00
tow_weight                  0.00
cargo_volume                0.00
price_per_range             0.00
germany_price_euros         5.70
netherlands_price_euros    10.07
uk_gbp                     27.26
availability                0.00
drive                       0.00
market_segment              0.00
seats                       0.00
heat_pump                   0.00
towbar                      0.00
safety_rating               0.00
dtype: float64

In [64]:
df["germany_price_euros"] = df["germany_price_euros"].fillna(df["germany_price_euros"].mode()[0])

In [65]:
df["netherlands_price_euros"] = df["netherlands_price_euros"].fillna(df["netherlands_price_euros"].mode()[0])

In [66]:
df["uk_gbp"] = df["uk_gbp"].fillna(df["uk_gbp"].mode()[0])

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 182250 entries, 0 to 182249
Data columns (total 20 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   name                     182250 non-null  object
 1   efficiency               182250 non-null  object
 2   real_range               182250 non-null  object
 3   weight                   182250 non-null  object
 4   acceleration             182250 non-null  object
 5   one_stop_range           182250 non-null  object
 6   fast_charge              182250 non-null  object
 7   tow_weight               182250 non-null  object
 8   cargo_volume             182250 non-null  object
 9   price_per_range          182250 non-null  object
 10  germany_price_euros      182250 non-null  object
 11  netherlands_price_euros  182250 non-null  object
 12  uk_gbp                   182250 non-null  object
 13  availability             182250 non-null  object
 14  drive                    182250 non-null  object
 15  market_segment           182250 non-null  object
 16  seats                    182250 non-null  int64
 17  heat_pump                182250 non-null  object
 18  towbar                   182250 non-null  object
 19  safety_rating            182250 non-null  int64
dtypes: int64(2), object(18)
memory usage: 27.8+ MB

In [68]:
df1 = pd.DataFrame()
df1

Empty DataFrame
Columns: []
Index: []

In [69]:
df1["brand_name"] = df["name"].apply(
    lambda x: re.match(r'^([^\s]+)\s+(.*)$', str(x)).group(1)
)

In [70]:
df1["model"] = df["name"].apply(
    lambda x: re.match(r'^([^\s]+)\s+(.*)$', str(x)).group(2)
)

In [71]:
df1["efficiency(Wh/km)"] = df["efficiency"].apply(lambda x : re.findall(r"\d+",x)[0]).astype("int")

In [72]:
df1["real_Range(km)"] = df["real_range"].apply(lambda x : re.findall(r"\d+",x)[0]).astype("int")

In [73]:
df1["weight(kg)"] = df["weight"].apply(lambda x : re.findall(r"[\d,]+", x)[0].replace(",", "")).astype("int")

In [74]:
df1["acceleration(sec)"]= df["acceleration"].apply(lambda x : re.findall(r'[\d.]+',x)[0]).astype("float")

In [75]:
df1["one_stop_range(km)"] = df["one_stop_range"].apply(lambda x : re.findall(r"\d+", x)[0]).astype("int")

In [76]:
df1["one_stop_range(km)"] = df["one_stop_range"].apply(lambda x : re.findall(r"\d+", x)[0]).astype("int")

In [77]:
df1["fast_charge(kWh)"] = df["fast_charge"].apply(lambda x : re.findall(r"[\d.]+", x)[0]).astype("float")

In [78]:
df["tow_weight"] = df["tow_weight"].replace(["unknown"],"0")

In [79]:
df1["tow_weight(kg)"] = df["tow_weight"].apply(lambda x : re.findall(r"[\d,]+", x)[0].replace(",", "")).astype("int")

In [80]:
df["cargo_volume"] = df["cargo_volume"].replace(["unknown"],"0")

In [81]:
df1["cargo_volume(L)"] = df["cargo_volume"].apply(lambda x : re.findall(r"\d+",x)[0]).astype("int")

In [82]:
df1.head()

,brand_name,model,efficiency(Wh/km),real_Range(km),weight(kg),acceleration(sec),one_stop_range(km),fast_charge(kWh),tow_weight(kg),cargo_volume(L)
0,Tesla,Model 3 RWD,218,275,1847,6.2,331,60.0,1000,682
1,BMW,iX3 50 xDrive,279,390,2360,4.9,478,108.7,2000,578
2,MG,MG4 Electric 64 kWh,280,220,1726,7.9,249,61.7,500,363
3,BMW,iX xDrive40,323,220,2440,6.1,237,71.0,2500,500
4,Fiat,500e Hatchback 42 kWh,257,145,1365,9.0,162,37.3,0,185

In [83]:
df["price_per_range "].unique()

array(['£125 /mi', '£155 /mi', '£147 /mi', '£320 /mi', '£181 /mi',
       '£198 /mi', '£178 /mi', '£156 /mi', '£173 /mi', '£165 /mi',
       '£128 /mi', '£142 /mi', '£170 /mi', '£199 /mi', '£188 /mi',
       '£139 /mi', '£127 /mi', '£166 /mi', '£154 /mi', '£135 /mi',
       '£652 /mi', '£150 /mi', '£116 /mi', '£247 /mi', '£122 /mi',
       '£161 /mi', '£126 /mi', '£159 /mi', '£143 /mi', '£212 /mi',
       '£167 /mi', '£467 /mi', '£132 /mi', '£129 /mi', '£201 /mi',
       '£175 /mi', '£157 /mi', '£117 /mi', '£164 /mi', '£163 /mi',
       '£131 /mi', '£187 /mi', '£172 /mi', '£137 /mi', '£136 /mi',
       '£119 /mi', '£169 /mi', '£152 /mi', '£363 /mi', '£261 /mi',
       '£158 /mi', '£197 /mi', '£120 /mi', '£134 /mi', '£209 /mi',
       '£180 /mi', '£141 /mi', '£171 /mi', '£217 /mi', '£299 /mi',
       '£192 /mi', '£160 /mi', '£300 /mi', '£144 /mi', '£203 /mi',
       '£149 /mi', '£185 /mi', '£189 /mi', '£207 /mi', '£183 /mi',
       '£138 /mi', '£332 /mi', '£262 /mi', '£296 /mi', '£301 /mi',
       '£290 /mi', '£182 /mi', '£315 /mi', '£586 /mi', '£193 /mi',
       '£146 /mi', '£302 /mi', '£145 /mi', '£162 /mi', '£211 /mi',
       '£240 /mi', '£295 /mi', '£204 /mi', '£151 /mi', '£259 /mi',
       '£227 /mi', '£236 /mi', '£285 /mi', '£179 /mi', '£123 /mi',
       '£177 /mi', '£392 /mi', '£148 /mi', '£223 /mi', '£1,174 /mi',
       '£626 /mi', '£220 /mi', '£242 /mi', '£268 /mi', '£316 /mi',
       '£176 /mi', '£191 /mi', '£235 /mi', '£344 /mi', '£303 /mi',
       '£237 /mi', '£168 /mi', '£274 /mi', '£205 /mi', '£219 /mi',
       '£194 /mi', '£200 /mi', '£314 /mi', '£133 /mi', '£282 /mi',
       '£249 /mi', '£215 /mi', '£293 /mi', '£190 /mi', '£228 /mi',
       '£264 /mi', '£110 /mi', '£270 /mi', '£349 /mi', '£362 /mi',
       '£277 /mi', '£195 /mi', '£383 /mi', '£256 /mi', '£284 /mi',
       '£350 /mi', '£234 /mi', '£202 /mi', '£174 /mi', '£226 /mi',
       '£214 /mi', '£225 /mi', '£271 /mi', '£382 /mi', '£312 /mi',
       '£208 /mi', '£184 /mi', '£269 /mi', '£351 /mi', '£310 /mi',
       '£436 /mi', '£153 /mi', '£186 /mi', '£231 /mi', '£325 /mi',
       '£651 /mi', '£233 /mi', '£424 /mi', '£206 /mi', '£464 /mi',
       '£397 /mi', '£246 /mi', '£250 /mi', '£279 /mi', '£253 /mi',
       '£346 /mi', '£266 /mi', '£371 /mi', '£273 /mi', '£276 /mi',
       '£222 /mi', '£376 /mi', '£402 /mi', '£254 /mi', '£328 /mi',
       '£345 /mi', '£400 /mi', '£196 /mi', '£341 /mi', '£229 /mi',
       '£695 /mi', '£291 /mi', '£289 /mi', '£503 /mi', '£358 /mi',
       '£265 /mi', '£213 /mi', '£244 /mi', '£238 /mi', '£313 /mi',
       '£210 /mi', '£526 /mi', '£263 /mi', '£334 /mi', '£373 /mi',
       '£771 /mi', '£275 /mi', '£292 /mi', '£245 /mi', '£283 /mi',
       '£331 /mi', '£130 /mi', '£336 /mi', '£288 /mi', '£454 /mi',
       '£518 /mi', '£232 /mi', '£218 /mi', '£308 /mi', '£340 /mi',
       '£258 /mi', '£243 /mi', '£216 /mi', '£287 /mi', '£221 /mi',
       '£257 /mi', '£267 /mi', '£359 /mi', '£674 /mi', '£549 /mi',
       '£414 /mi', '£385 /mi', '£390 /mi', '£294 /mi', '£391 /mi',
       '£408 /mi', '£415 /mi', '£352 /mi', '£140 /mi', '£541 /mi',
       '£348 /mi', '£255 /mi', '£329 /mi', '£224 /mi', '£252 /mi',
       '£306 /mi', '£458 /mi', '£241 /mi', '£461 /mi', '£519 /mi',
       '£494 /mi', '£404 /mi', '£369 /mi', '£379 /mi', '£248 /mi',
       '£251 /mi', '£381 /mi', '£427 /mi', '£450 /mi', '£430 /mi',
       '£366 /mi', '£505 /mi', '£272 /mi', '£327 /mi', '£485 /mi',
       '£501 /mi', '£411 /mi', '£353 /mi', '£322 /mi', '£338 /mi',
       '£333 /mi', '£307 /mi', '£321 /mi', '£688 /mi', '£419 /mi',
       '£437 /mi', '£462 /mi', '£323 /mi', '£239 /mi', '£442 /mi',
       '£448 /mi', '£743 /mi', '£432 /mi', '£444 /mi', '£395 /mi',
       '£446 /mi', '£280 /mi', '£387 /mi', '£355 /mi', '£343 /mi',
       '£452 /mi', '£354 /mi', '£367 /mi', '£309 /mi', '£628 /mi',
       '£542 /mi', '£347 /mi', '£459 /mi', '£388 /mi', '£364 /mi',
       '£396 /mi', '£361 /mi', '£305 /mi', '£465 /mi', '£324 /mi',
       '£471 /mi', '£507 /mi', '£676 /mi', '£495 /mi', '£410 /mi',
       '£342 /mi', '£260 /mi', '£326 /mi', '£377 /mi', '£493 /mi',
       '£386 /mi', '£429 /mi', '£422 /mi', '£428 /mi', '£418 /mi',
       '£318 /mi', '£360 /mi', '£365 /mi', '£337 /mi', '£281 /mi',
       '£317 /mi', '£578 /mi', '£492 /mi', '£441 /mi', '£356 /mi',
       '£319 /mi', '£470 /mi', '£431 /mi', '£380 /mi', '£531 /mi',
       '£440 /mi', '£412 /mi', '£409 /mi', '£671 /mi', '£601 /mi',
       '£403 /mi', '£684 /mi', '£368 /mi', '£484 /mi', '£473 /mi',
       '£384 /mi', '£545 /mi', '£426 /mi', '£486 /mi', '£457 /mi',
       '£406 /mi', '£298 /mi', '£375 /mi', '£561 /mi', '£407 /mi',
       '£453 /mi', '£466 /mi', '£683 /mi', '£374 /mi', '£398 /mi',
       '£389 /mi', '£416 /mi', '£480 /mi', '£447 /mi', '£443 /mi',
       '£451 /mi'], dtype=object)

In [84]:
df.columns

Index(['name', 'efficiency', 'real_range', 'weight', 'acceleration',
       'one_stop_range', 'fast_charge', 'tow_weight', 'cargo_volume',
       'price_per_range ', 'germany_price_euros', 'netherlands_price_euros',
       'uk_gbp', 'availability', 'drive', 'market_segment', 'seats',
       'heat_pump', 'towbar', 'safety_rating'],
      dtype='object')

In [85]:
df.columns = df.columns.str.strip()

In [86]:
df1['price_per_range(€/km)']  = df["price_per_range"].apply(lambda x : re.findall(r"\d+",x)[0]).astype("int")

In [87]:
df1["germany_price(euros)"] = df["germany_price_euros"].apply(lambda x : re.findall(r"[\d,]+",x)[0].replace(",","")).astype(int)

In [88]:
df1["netherlands_price_(€)"] = df["netherlands_price_euros"].apply(lambda x : re.findall(r"[\d,]+",x)[0].replace(",","")).astype(int)

In [89]:
df1["uk_gbp"] = df["uk_gbp"].apply(lambda x : re.findall(r"[\d,]+",x)[0].replace(",","")).astype(int)

In [90]:
df1['availability'] = df['availability'].apply(
    lambda x: re.findall(r'^[^\s]+', str(x))[0].strip()
)

In [91]:
df1['period'] = df['availability'].apply(
    lambda x: (
        re.findall(r'(?:since|from)\s+(.*?)(?:\*|$)', str(x))[0]
        if re.findall(r'(?:since|from)\s+(.*?)(?:\*|$)', str(x))
        else (
            re.findall(r'\((.*?)\)', str(x))[0]
            if re.findall(r'\((.*?)\)', str(x))
            else None
        )
    )
)

In [92]:
df1['start_period'] = df1['period'].apply(
    lambda x: re.findall(r'^(.*?)\s*(?:-|$)', str(x))[0].strip()
)

In [93]:
df1['end_period'] = df1['period'].apply(
    lambda x: (
        re.findall(r'-\s*(.*)$', str(x))[0]
        if re.findall(r'-\s*(.*)$', str(x))
        else 'Present'
    )
)

In [94]:
df1["drive_type"] = df["drive"].apply(
    lambda x: re.findall(r"^\S+", str(x))[0]
).astype(str)

In [95]:
df1["market_segment"] = df["market_segment"]

In [96]:
df1["seats"] = df["seats"]

In [97]:
df["heat_pump"].unique()

array(['Heat pump available', 'Heat pump not available'], dtype=object)

In [98]:
def heat_pump(pump):
  if pump == "Heat pump available":
    return "Yes"
  else:
    return "No"

In [99]:
df1["heat_pump_availability"] = df["heat_pump"].apply(heat_pump)

In [100]:
df["towbar"].unique()

array(['Towbar possible', 'Towbar not possible'], dtype=object)

In [101]:
def tow_bar(bar):
  if bar == "Towbar possible":
    return "Yes"
  else:
    return "No"

In [102]:
df1["towbar_possible"] = df["towbar"].apply(tow_bar)

In [103]:
df["safety_rating"].unique()

array([-1,  5,  4,  3,  0,  1])

In [104]:
def safety_rating(rating):
  if rating < 0:
    return 0
  else:
    return rating

In [105]:
df1["safety_rating"] = df["safety_rating"].apply(safety_rating)

In [106]:
df1.shape

(182250, 24)

In [107]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 182250 entries, 0 to 182249
Data columns (total 24 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   brand_name              182250 non-null  object
 1   model                   182250 non-null  object
 2   efficiency(Wh/km)       182250 non-null  int64
 3   real_Range(km)          182250 non-null  int64
 4   weight(kg)              182250 non-null  int64
 5   acceleration(sec)       182250 non-null  float64
 6   one_stop_range(km)      182250 non-null  int64
 7   fast_charge(kWh)        182250 non-null  float64
 8   tow_weight(kg)          182250 non-null  int64
 9   cargo_volume(L)         182250 non-null  int64
 10  price_per_range(€/km)   182250 non-null  int64
 11  germany_price(euros)    182250 non-null  int64
 12  netherlands_price_(€)   182250 non-null  int64
 13  uk_gbp                  182250 non-null  int64
 14  availability            182250 non-null  object
 15  period                  182250 non-null  object
 16  start_period            182250 non-null  object
 17  end_period              182250 non-null  object
 18  drive_type              182250 non-null  object
 19  market_segment          182250 non-null  object
 20  seats                   182250 non-null  int64
 21  heat_pump_availability  182250 non-null  object
 22  towbar_possible         182250 non-null  object
 23  safety_rating           182250 non-null  int64
dtypes: float64(2), int64(12), object(10)
memory usage: 33.4+ MB

In [108]:
df1 = df1.drop(columns = ["period"])

In [109]:
df1.head()

,brand_name,model,efficiency(Wh/km),real_Range(km),weight(kg),acceleration(sec),one_stop_range(km),fast_charge(kWh),tow_weight(kg),cargo_volume(L),...,uk_gbp,availability,start_period,end_period,drive_type,market_segment,seats,heat_pump_availability,towbar_possible,safety_rating
0,Tesla,Model 3 RWD,218,275,1847,6.2,331,60.0,1000,682,...,37990,Available,December 2025,Present,Rear,D,5,Yes,Yes,0
1,BMW,iX3 50 xDrive,279,390,2360,4.9,478,108.7,2000,578,...,58755,Available,September 2025,Present,All,D,5,Yes,Yes,0
2,MG,MG4 Electric 64 kWh,280,220,1726,7.9,249,61.7,500,363,...,29745,Discontinued,October 2022,February 2026,Rear,C,5,Yes,Yes,5
3,BMW,iX xDrive40,323,220,2440,6.1,237,71.0,2500,500,...,69905,Discontinued,October 2021,January 2025,All,E,5,Yes,Yes,5
4,Fiat,500e Hatchback 42 kWh,257,145,1365,9.0,162,37.3,0,185,...,23995,Available,November 2020,Present,Front,B,4,No,No,4

In [110]:
df1.duplicated().sum()

np.int64(180900)

In [111]:
df1 = df1.drop_duplicates()

In [112]:
df1.to_csv("cleaned_EV_Dataset3.csv", index = False)